---
- name: Install nginx configuration
  template:
    src: wordpress.conf
    dest: /etc/nginx/sites-available/wordpress.conf
  notify: restart nginx

- name: activate site configuration
  file:
    src: '/etc/nginx/sites-available/wordpress.conf'
    dest: '/etc/nginx/sites-enabled/wordpress.conf'
    state: 'link'

- name: Download WordPress
  get_url:
    url: "{{ download_url }}"
    dest: "/home/ubuntu/latest.tar.gz"

- name: Creating directory for Wordpress
  file:
    path: "{{ wpdirectory }}"
    state: "directory"
    owner: "www-data"
    group: "www-data"

- name: Creating directory to s3
  file:
    path: /var/www
    state: "directory"
    owner: "www-data"
    group: "www-data"

- name: unarchive
  unarchive:
    src: /home/ubuntu/latest.tar.gz
    dest: /var/www/html/
    extra_opts: [--strip-components=1]
    remote_src: yes

- name: copy config file for Wordpress
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php
  notify: restart nginx

- name: delete apache2
  apt: name=apache2 state=absent
  notify: restart nginx
